Repository NikBenson/pointerNames, pull requests merged in 2020-06, with the labels that each got.

#5 splitted filtstructure into src/ & tests/, updated CMake
  CMakeLists.txt
  Makefile.am
  src/CMakeLists.txt
  src/library.c
  src/library.h
  tests/CMakeLists.txt
  tests/check_convert.c
Labels: enhancement

#7 CMake check
  CMakeLists.txt
  Makefile.am
  cmake/FindCheck.cmake
  cmake/config.h.in
  src/CMakeLists.txt
Labels: enhancement

#3 Create c-cpp.yml
  .github/workflows/c-cpp.yml
Labels: enhancement

#8 created convert unit test
  src/library.h
  tests/CMakeLists.txt
  tests/check_convert.c
Labels: enhancement

#10 create a default names array
  src/library.c
Labels: enhancement

#13 Create SECURITY.md
  SECURITY.md
Labels: enhancement

#16 commented library.h
  src/library.c
  src/library.h
Labels: documentation

#17 commented library.c
  src/library.c
Labels: documentation

#19 implemented pointerToNames
  src/library.c
  src/library.h
Labels: bug, enhancement
